Package, Repository
pipewire, arch
libgtop, arch
bluez, arch
bluez-utils, arch
btop, arch
networkmanager, arch
dart-sass, arch
wl-clipboard, arch
brightnessctl, arch
swww, arch
python, arch
gnome-bluetooth-3.0, arch
pacman-contrib, arch
power-profiles-daemon, arch
gvfs, arch
grimblast-git, aur
gpu-screen-recorder, aur
hyprpicker, aur
matugen-bin, aur
python-gpustat, aur
aylurs-gtk-shell-git, aur
pywal, aur
